name: yammi
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0  
  flutter_easyloading: ^3.0.0
  get_it: ^7.1.3
  injectable: ^1.4.1
  intl_phone_number_input: ^0.7.0+2
  json_annotation: ^4.0.1
  pin_code_fields: ^7.1.0
  retrofit: ^2.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  auto_route_generator: ^2.1.0  
  build_runner:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.2  
  lint: ^1.5.3  
  mocktail: ^0.1.2
  retrofit_generator: ^2.0.0 

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700  